### ISSUE TITLE
About gradient calculation in backward.cu renderCUDA()

### ISSUE THREAD

**Issue by ZilingLiu** [RaymondJiangkw/COGS#16]
Thank you for your great work! While reviewing the gradient calculation from lines L766 to L774 in backward.cu, I’m unclear about the use of out_xy and out_depth. I didn’t initially realize these variables were necessary during differentiation. Could you clarify their purpose in this part of the gradient computation?

**Comment by RaymondJiangkw** [comment]
Hi! Thanks for your interest! They arise actually because the rendering of depth and screen-space coordinates (xy) are alpha-blended depth and xy divided by the accumulated alpha in the implementation, instead of alpha-blended depth and xy alone. You can find relevant lines in L472 - L482 of `forward.cu`.

The reason is that, for example, if there is only one Gaussian kernel with 0.5 opacity, without division by accumulated alpha, the depth or xy will not be accurate, i.e., $x * 0.5 \neq x$. But we only use the rendering of depth and xy in the coarse solution construction stage and we initialize all the Gaussians to be fully opaque. So it should not make a difference.

**Comment by ZilingLiu** [comment]
Thank you for your explaination. However I still have some problem. In my understanding, for each ray, all the intersected points will be projected to the same pixel coordinate. Therefore, will last_xy[ch] = inter_screen_point[ch] - out_xy[ch] always equal 0? Still a little confused.

**Comment by RaymondJiangkw** [comment]
Oh, yes, you are right. The rendered xy = $\frac{\sum_{i=1}^N xy_i o_i \prod_{j=1}^{i-1} (1-o_j)}{\sum_{i=1}^N o_i \prod_{j=1}^{i-1} (1-o_j)}$. Since $xy_i$ is always the same, the rendered xy = $xy\frac{\sum_{i=1}^N o_i \prod_{j=1}^{i-1} (1-o_j)}{\sum_{i=1}^N o_i \prod_{j=1}^{i-1} (1-o_j)}=xy$. So it is irrelevant to the opacity and therefore irrelevant to the alpha. It is indeed always zero and that code part is redundant.
